import type { Env } from "./helpers";

export interface Field {
  key: string;
  /** Prompt with masked input */
  secret?: boolean;
  /** Push to the worker via `wrangler secret bulk` */
  worker?: boolean;
  /** Where to find the value — shown in the wizard prompt */
  help: string;
}

export type ValidationResult =
  | { ok: true; derived?: Record<string, string> }
  | { ok: false; message: string };

export interface Group {
  name: string;
  required: boolean;
  /** What degrades when an optional group is skipped */
  skipNote?: string;
  fields: Field[];
  validate?: (env: Env) => Promise<ValidationResult>;
}

/*
 * Credential groups — the single source of truth for the setup wizard.
 * Each field declares where its value flows; the wizard prompts for it,
 * validates it against the provider's API, and persists it to .env.
 */
// Neon and Cloudflare are authenticated via OAuth CLI login (`neon auth`,
// `wrangler login`) in scripts/lib/auth.ts, not prompted for here.
export const GROUPS: Group[] = [
  {
    name: "Terra",
    required: true,
    fields: [
      {
        key: "TERRA_DEV_ID",
        worker: true,
        help: "dashboard.tryterra.co → API Keys → Developer ID",
      },
      {
        key: "TERRA_API_KEY",
        secret: true,
        worker: true,
        help: "dashboard.tryterra.co → API Keys → API Key",
      },
      {
        key: "TERRA_WEBHOOK_SECRET",
        secret: true,
        worker: true,
        help: "dashboard.tryterra.co → Connections → Webhook → Edit destination credentials → Signing Secret",
      },
    ],
    async validate(env) {
      const res = await fetch(
        "https://access.tryterra.co/api/v2/subscriptions",
        {
          headers: {
            "dev-id": env.TERRA_DEV_ID,
            "x-api-key": env.TERRA_API_KEY,
          },
        },
      );
      if (!res.ok) {
        return {
          ok: false,
          message:
            "TERRA_DEV_ID or TERRA_API_KEY is invalid.\n" +
            "  Verify at dashboard.tryterra.co → Settings",
        };
      }
      return { ok: true };
    },
  },
  // Anthropic is gated by the AI opt-in in setup.ts, not prompted here.
  {
    name: "SendGrid",
    required: false,
    skipNote: "OTP codes will log to the console instead of emailing",
    fields: [
      {
        key: "SENDGRID_API_KEY",
        secret: true,
        worker: true,
        help: "app.sendgrid.com → Settings → API Keys",
      },
      {
        key: "SENDGRID_FROM_EMAIL",
        worker: true,
        help: "A SendGrid verified sender address",
      },
    ],
  },
];

/** Keys that must be present before setup or secret syncing can proceed. */
export const REQUIRED_KEYS = GROUPS.filter((g) => g.required).flatMap((g) =>
  g.fields.map((f) => f.key),
);

// Generated by setup rather than prompted, but routed to the same destinations
const GENERATED: Pick<Field, "key" | "worker">[] = [
  { key: "BETTER_AUTH_SECRET", worker: true },
];

const ALL_FIELDS = [...GROUPS.flatMap((g) => g.fields), ...GENERATED];

// DATABASE_URL and ANTHROPIC_API_KEY aren't wizard fields, so list them here.
export const WORKER_SECRETS = [
  "DATABASE_URL",
  "ANTHROPIC_API_KEY",
  ...ALL_FIELDS.filter((f) => f.worker).map((f) => f.key),
];
