/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/orders/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Serve kit activation page
         * @description Returns an HTML page for end users to activate their test kit and provide test-taker information
         */
        get: {
            parameters: {
                query: {
                    /** @description Supplier Kit ID from test kit packaging */
                    kit_id: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description HTML activation form */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/html": string;
                    };
                };
                /** @description Invalid kit ID */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/html": components["schemas"]["ProblemDetail"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/html": components["schemas"]["ProblemDetail"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Activate a test kit
         * @description Registers test-taker details with the supplier and updates order item status. This endpoint is called after the test-taker receives their kit and provides their information.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Activation details including test-taker info */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ActivationContextDTO"];
                };
            };
            responses: {
                /** @description Kit activated successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ActivateKitResponse"];
                    };
                };
                /** @description Invalid request body or kit already activated */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetail"];
                    };
                };
                /** @description Kit not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetail"];
                    };
                };
                /** @description Kit already activated */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetail"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetail"];
                    };
                };
                /** @description Supplier service unavailable */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetail"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clients/webhook-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the registered webhook URL
         * @description The currently registered webhook destination for this environment ("" when none).
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current destination */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ClientResponse"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetail"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update webhook URL
         * @description Update or clear the webhook URL for the authenticated client. The
         *     webhook URL must use HTTPS if provided, or can be empty to clear it.
         *     Note this means webhooks will no longer be sent to your previous
         *     endpoint.
         *
         *     Deliveries to your endpoint carry an `X-Terra-Signature` header of the
         *     form `t=<timestamp>,v1=<hex-hmac>` where `t` is the send time in Unix
         *     seconds and `v1` is `HMAC-SHA256(secret, t + "." + payload)` — the
         *     same scheme as all Terra webhooks. Verify by recomputing the HMAC
         *     from the received `t` and the raw body.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Webhook URL update request */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateWebhookUrlRequest"];
                };
            };
            responses: {
                /** @description Webhook URL updated successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ClientResponse"];
                    };
                };
                /** @description Bad request - invalid URL format or validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetail"];
                    };
                };
                /** @description Unauthorized - invalid client credentials */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthenticationError"];
                    };
                };
                /** @description Client not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetail"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetail"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/v1/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List orders
         * @description Keyset-paginated index of your orders, newest first. Pass the returned next_cursor to fetch the following page; absence of next_cursor means the last page.
         */
        get: {
            parameters: {
                query?: {
                    limit?: number;
                    /** @description order_id from the previous page's next_cursor */
                    cursor?: string;
                    /** @description Only orders created at/after this RFC3339 timestamp. */
                    since?: string;
                    /** @description true = only delivered/completed orders with at least one item whose results aren't in yet (the overview's "missing results" set). */
                    missing?: boolean;
                    /** @description Filter by order status string (e.g. order.processing) */
                    status?: string;
                    collection_type?: "AT_HOME" | "GO_TO_LAB";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description One page of orders */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ListOrdersResponse"];
                    };
                };
                /** @description Invalid pagination or filter parameters */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetail"];
                    };
                };
                /** @description Missing or invalid credentials */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetail"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetail"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create a new order
         * @description Create a new blood, DNA, or device test order. Products that are disabled in your catalog cannot be ordered and are rejected with 403. Payment is authorized then captured as part of order creation; if authorization fails, nothing is created and a 402 is returned.
         */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Optional Stripe-style idempotency key. Replaying the same key with the same request body returns the original order without creating or charging again; the same key with a different body returns 409. */
                    "Idempotency-Key"?: string;
                };
                path?: never;
                cookie?: never;
            };
            /** @description Order creation request */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateOrderRequest"];
                };
            };
            responses: {
                /** @description Order created successfully */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CreateOrderResponse"];
                    };
                };
                /** @description Bad request - invalid JSON or validation errors */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CreateOrderValidationError"];
                    };
                };
                /** @description Payment authorization failed. Nothing was created — no supplier order and no charge. Retry after resolving the payment method. */
                402: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaymentRequiredProblem"];
                    };
                };
                /** @description A requested product is not enabled in your catalog */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetail"];
                    };
                };
                /** @description The Idempotency-Key was already used with a different request body, or a request with this key is still in progress. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetail"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetail"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{orderID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get order by order ID
         * @description Returns complete order details including items, recipient, and status
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Order ID */
                    orderID: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successfully retrieved order */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GetOrderResponse"];
                    };
                };
                /** @description Invalid order ID format */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetail"];
                    };
                };
                /** @description Unauthorized - invalid credentials */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthenticationError"];
                    };
                };
                /** @description Order not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetail"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetail"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{orderID}/simulate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Simulate an order lifecycle event (Testing environment only)
         * @description Drives one lifecycle event on your order exactly as a supplier update would — status history is recorded and the corresponding signed webhook is delivered to your registered destination. Only valid forward transitions are accepted. results_ready also stores a sample result so the download and acknowledge flows work end to end. The production environment refuses with 403.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orderID: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SimulateOrderRequest"];
                };
            };
            responses: {
                /** @description Event applied */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SimulateOrderResponse"];
                    };
                };
                /** @description Invalid order id, request body, order_item_id, or event */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetail"];
                    };
                };
                /** @description Not available in the production environment */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetail"];
                    };
                };
                /** @description Order (or order item) not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetail"];
                    };
                };
                /** @description Event is not a valid transition from the current status */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SimulateTransitionProblem"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetail"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all product types
         * @description Returns all available diagnostic test categories (e.g., Blood Tests, DNA Tests)
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successfully retrieved product types */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProductType"][];
                    };
                };
                /** @description Unauthorized - invalid credentials */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthenticationError"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetail"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/selection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Set catalog selection
         * @description Curate which products your own catalog reads return. Full-set write: listed products become enabled, every other product disabled. With no selection saved, everything is enabled; products added to the global catalog after your last save default to enabled until you save again. Disabled products are excluded from catalog reads and cannot be ordered (403).
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateCatalogSelectionRequest"];
                };
            };
            responses: {
                /** @description Selection saved */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UpdateCatalogSelectionResponse"];
                    };
                };
                /** @description Invalid request body */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetail"];
                    };
                };
                /** @description Missing or invalid credentials */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetail"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetail"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get products by type ID
         * @description Returns all products within a specific product type category
         */
        get: {
            parameters: {
                query?: {
                    /** @description Return the full catalog with per-product enabled flags (curation view). */
                    show_all?: boolean;
                };
                header?: never;
                path: {
                    /** @description Product Type ID */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successfully retrieved products. An existing product type with no available products returns an empty array. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Product"][];
                    };
                };
                /** @description Invalid product type ID format */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetail"];
                    };
                };
                /** @description Unauthorized - invalid credentials */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthenticationError"];
                    };
                };
                /** @description Product type not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Product type id 100 not found */
                            detail: string;
                            /** @example /api/v1/products/100 */
                            instance: string;
                            /** @example 404 */
                            status: number;
                            /** @example Resource Not Found */
                            title: string;
                            /** @example https://api.terra-diagnostics.com/errors/not-found-error */
                            type: string;
                        };
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetail"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/{id}/variants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get product variants by product ID
         * @description Returns all available variants/options for a specific diagnostic test product (e.g., different panel sizes, customizations)
         */
        get: {
            parameters: {
                query?: {
                    /** @description Include variants of catalog-disabled products (curation view). Disabled products remain non-orderable regardless. */
                    show_all?: boolean;
                };
                header?: never;
                path: {
                    /** @description Product ID */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successfully retrieved variants */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProductVariant"][];
                    };
                };
                /** @description Invalid product ID format */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetail"];
                    };
                };
                /** @description Unauthorized - invalid credentials */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthenticationError"];
                    };
                };
                /** @description No product variants were found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Product variant id 100 not found */
                            detail: string;
                            /** @example /api/v1/products/100/variants */
                            instance: string;
                            /** @example 404 */
                            status: number;
                            /** @example Resource Not Found */
                            title: string;
                            /** @example https://api.terra-diagnostics.com/errors/not-found-error */
                            type: string;
                        };
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetail"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List results
         * @description Keyset-paginated index of order items with result activity, newest first.
         */
        get: {
            parameters: {
                query?: {
                    limit?: number;
                    /** @description order_item_id from the previous page's next_cursor */
                    cursor?: string;
                    /** @description Filter by results status string (e.g. results.results_ready) */
                    status?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description One page of results */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ListResultsResponse"];
                    };
                };
                /** @description Invalid pagination or filter parameters */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetail"];
                    };
                };
                /** @description Missing or invalid credentials */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetail"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetail"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/results/{orderItemID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get presigned URL for test results
         * @description Returns a time-limited presigned URL to download normalized test results in FHIR format (JSON). The URL is valid for 15 minutes. Note: Every orderItemID can only be associated with maximum 1 panel, hence results can be uniquely identified by orderItemID.
         */
        get: {
            parameters: {
                query: {
                    /** @description Test Taker ID */
                    test_taker_id: number;
                };
                header?: never;
                path: {
                    /** @description Order Item ID */
                    orderItemID: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successfully generated download URL */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GetResultsURLResponse"];
                    };
                };
                /** @description Invalid or missing order item ID */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetail"];
                    };
                };
                /** @description Unauthorized - invalid client credentials */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthenticationError"];
                    };
                };
                /** @description Results not found for this order item */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetail"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetail"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/results/{orderItemID}/acknowledge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Acknowledge results receipt
         * @description Records the end user's affirmative confirmation that they have received and viewed their results (Schedule C §C6A). Must be triggered by an explicit end-user action (e.g. a checkbox or button in the client's UI) — never automatically by the backend on retrieval or delivery. Required for compliance and audit trails.
         */
        post: {
            parameters: {
                query: {
                    /** @description Test Taker ID */
                    test_taker_id: number;
                };
                header?: never;
                path: {
                    /** @description Order Item ID */
                    orderItemID: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Results acknowledged successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AcknowledgeResultsResponse"];
                    };
                };
                /** @description Invalid order item ID */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetail"];
                    };
                };
                /** @description Unauthorized - invalid credentials */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthenticationError"];
                    };
                };
                /** @description Order item not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetail"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetail"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/labs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List nearby lab draw sites
         * @description Returns nearby Patient Service Centers (lab draw sites) for a US zip code, used when placing a GO_TO_LAB order.
         */
        get: {
            parameters: {
                query: {
                    /** @description 5-digit US zip (optionally with 4-digit suffix) */
                    zip_code: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Nearby lab draw sites */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ListLabsResponse"];
                    };
                };
                /** @description Missing or invalid zip code */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetail"];
                    };
                };
                /** @description Missing or invalid credentials */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetail"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetail"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Analytics overview
         * @description Client-scoped analytics summary for a time window: order totals with a by-status breakdown, results in vs. still missing, and webhook failures with a daily series.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Start of the window (RFC3339). Defaults to until minus 7 days. */
                    since?: string;
                    /** @description End of the window (RFC3339). Defaults to now. */
                    until?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Analytics summary */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OverviewResponse"];
                    };
                };
                /** @description Invalid time window */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetail"];
                    };
                };
                /** @description Missing or invalid credentials */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetail"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetail"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/webhook-deliveries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List webhook delivery outcomes
         * @description Client-scoped keyset list of terminal webhook delivery outcomes, newest first. Use outcome=failed to see only permanently-failed deliveries.
         */
        get: {
            parameters: {
                query?: {
                    /** @description One delivery outcome, or "failed" (rejected|invalid|dead_lettered). */
                    outcome?: "delivered" | "rejected" | "invalid" | "dead_lettered" | "replayed" | "failed";
                    limit?: number;
                    /** @description event_id from the previous page's next_cursor */
                    cursor?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description One page of delivery outcomes */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WebhookDeliveriesResponse"];
                    };
                };
                /** @description Invalid pagination or filter parameters */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetail"];
                    };
                };
                /** @description Missing or invalid credentials */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetail"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetail"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export interface webhooks {
    "order.status_changed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Order fulfilment status changed
         * @description Sent when an order's fulfilment status changes. `data.status` uses the same `order.*` vocabulary as REST reads of the order.
         *
         *     Deliveries carry `X-Terra-Signature: t=<unix_seconds>,v1=<hex>` where `v1 = HMAC-SHA256(signing_secret, "<t>.<raw_body>")` — verify against the raw body before trusting the payload — plus `X-Terra-Trace-Id` (the event_id). Delivery is at-least-once: dedupe on `event_id`. On network errors/408/429/5xx an event gets up to 5 HTTP attempts with exponential backoff (~1s, 2s, 4s, 8s) on first delivery, then single re-attempts with growing delays (5s doubling, capped at 10 minutes) for up to 10 deliveries in total — at most ~14 calls spread over ~30 minutes — before dead-lettering. Other 4xx responses are recorded as rejected and not retried at all.
         */
        post: operations["webhookOrderStatusChanged"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "order_item.results_status_change": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Order item results status changed
         * @description Sent when an order item's results status changes. `data.results_status` uses the `results.*` vocabulary shared with REST reads.
         *
         *     Signing, `X-Terra-Trace-Id`, at-least-once delivery, and retry semantics are identical to `order.status_changed` — see its description.
         */
        post: operations["webhookOrderItemResultsStatusChange"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export interface components {
    schemas: {
        ListOrdersResponse: {
            orders: components["schemas"]["OrderSummary"][];
            /**
             * @description Pass as ?cursor= for the next page; absent on the last page.
             * @example 333410942627700736
             */
            next_cursor?: string;
        };
        OrderSummary: {
            /** @example 333410942627700736 */
            order_id: string;
            /** @example ORDER-2024-001 */
            client_order_reference_id?: string;
            /** Format: date-time */
            created_at: string;
            /** @enum {string} */
            collection_type: "AT_HOME" | "GO_TO_LAB";
            /** @example order.payment_processing */
            order_status: string;
            /** @example 5540 */
            total_cents: number;
            /**
             * @description ISO-4217 numeric
             * @example 840
             */
            currency: number;
            items: components["schemas"]["OrderSummaryItem"][];
        };
        OrderSummaryItem: {
            /** @example 333410942627700737 */
            order_item_id: string;
            /** @example 100011 */
            variant_id: string;
            /** @example General Health */
            product_name?: string;
            /** @example 1 */
            item_status: number;
            /** @example results.awaiting_sample */
            results_status: string;
            /** @example 333410942627700738 */
            test_taker_id?: string;
        };
        ListResultsResponse: {
            results: components["schemas"]["ResultSummary"][];
            /**
             * @description Pass as ?cursor= for the next page; absent on the last page.
             * @example 333410942627700737
             */
            next_cursor?: string;
        };
        ResultSummary: {
            /** @example 333410942627700737 */
            order_item_id: string;
            /** @example 333410942627700736 */
            order_id: string;
            /** @example 100011 */
            variant_id: string;
            /** @example General Health */
            product_name?: string;
            /** @example results.results_ready */
            results_status: string;
            is_acknowledged: boolean;
            /** @example 333410942627700738 */
            test_taker_id?: string;
            /** Format: date-time */
            updated_at: string;
        };
        ClientResponse: {
            /** @example client_abc123 */
            client_id?: string;
            /** @example cust_xyz789 */
            customer_id?: string;
            /** @example https://your-domain.com/webhooks/terra */
            webhook_url?: string;
        };
        SimulateOrderRequest: {
            /**
             * @description Lifecycle event to apply.
             * @enum {string}
             */
            event: "payment_complete" | "payment_failed" | "processing" | "delayed" | "cancelled" | "delivery_fulfilled" | "completed" | "kit_activated" | "sample_processing_in_lab" | "sample_rejected" | "partial_results_ready" | "results_ready" | "lab_processing_error" | "escalation_raised";
            /**
             * @description Narrow a results event to one order item.
             * @example 333410942627700737
             */
            order_item_id?: string;
        };
        SimulateOrderResponse: {
            /** @example 333410942627700736 */
            order_id: string;
            /** @example delivery_fulfilled */
            applied_event: string;
        };
        UpdateCatalogSelectionRequest: {
            /** @description Products to enable; everything else is disabled. */
            product_ids: string[];
        };
        UpdateCatalogSelectionResponse: {
            /** @example 12 */
            enabled_count: number;
        };
        UpdateWebhookUrlRequest: {
            /** @example https://your-domain.com/webhooks/terra */
            webhook_url?: string;
        };
        /** @description Physical address for shipping test kits */
        AddressDTO: {
            /** @example 123 Baker Street */
            address_line_1: string;
            /** @example Flat 4B */
            address_line_2?: string;
            /** @example Greater London */
            administrative_area: string;
            /** @example London */
            city: string;
            /**
             * @description ISO 3166-1 alpha-2 (e.g., "GB", "US")
             * @example GB
             */
            country_code: string;
            /** @example 987654321 */
            id?: number;
            /** @example true */
            is_validated?: boolean;
            /** @example NW1 6XE */
            postal_code: string;
        };
        /** @description The recipient who will receive the test kit and may or may not be the test-taker (supplier-dependent) */
        RecipientDTO: {
            /** @example 1990-05-15 */
            date_of_birth: string;
            /** @example sarah.johnson@example.com */
            email: string;
            /** @example Sarah */
            first_name: string;
            /**
             * @example female
             * @enum {string}
             */
            gender_at_birth: "male" | "female";
            /** @example 123456789 */
            id?: string;
            /** @example Johnson */
            last_name: string;
            /**
             * @description Full E.164 phone number as stored and dialed, including the "+" and country calling code (e.g. "+447911123456"). Leading zeros significant to the national number are preserved.
             * @example +447911123456
             */
            phone_number: string;
        };
        /** @description Recipient on an order-creation request. phone_number is a single E.164 string; the separate country_code field was removed and is silently ignored if still sent. */
        RecipientRequestDTO: {
            /** @example 1990-05-15 */
            date_of_birth: string;
            /** @example sarah.johnson@example.com */
            email: string;
            /** @example Sarah */
            first_name: string;
            /**
             * @example female
             * @enum {string}
             */
            gender_at_birth: "male" | "female";
            /** @example 123456789 */
            id?: string;
            /** @example Johnson */
            last_name: string;
            /**
             * @description Required, in E.164 format: a leading "+", the country calling code, then the national number (e.g. "+447911123456"). A bare national number or a separate country_code is rejected.
             * @example +447911123456
             */
            phone_number: string;
        };
        /** @description Standard error response format following RFC 7807 specification */
        ProblemDetail: {
            /** @example One or more required fields are missing or invalid */
            detail?: string;
            /** @example /orders/create */
            instance?: string;
            /** @example 400 */
            status?: number;
            /** @example Validation Error */
            title?: string;
            /** @example https://terra.dev/errors/validation-error */
            type?: string;
        };
        /** @description 422 returned by the simulate endpoint when the requested event is not a valid forward transition from the current status. The RFC 7807 problem fields plus the two fields a client needs to recover without a GET round-trip. (Flat rather than an allOf over ProblemDetail: the conformance gate seals declared objects, and sealed allOf branches reject each other's properties.) */
        SimulateTransitionProblem: {
            /** @example event "payment_complete" is not a valid transition from the order's current status */
            detail?: string;
            /** @example /orders/333410942627700736/simulate */
            instance?: string;
            /** @example 422 */
            status?: number;
            /** @example Unprocessable Entity */
            title?: string;
            /** @example https://terra.dev/errors/business-logic-error */
            type?: string;
            /**
             * @description The status the rejected event was evaluated against.
             * @example order.payment_complete
             */
            current_status: string;
            /**
             * @description Events accepted from current_status, sorted.
             * @example [
             *       "processing",
             *       "cancelled"
             *     ]
             */
            valid_events: string[];
        };
        /** @description 402 returned by POST /orders when payment authorization fails. Nothing is created — no supplier order and no charge. The RFC 7807 problem fields plus a category the client can branch on. (Flat rather than an allOf over ProblemDetail: the conformance gate seals declared objects, and sealed allOf branches reject each other's properties.) */
        PaymentRequiredProblem: {
            /** @example Payment could not be authorized for this order. */
            detail: string;
            /** @example /api/v1/orders */
            instance?: string;
            /** @example 402 */
            status: number;
            /** @example Payment Required */
            title: string;
            /** @example https://api.terra-diagnostics.com/errors/payment-required-error */
            type: string;
            /**
             * @description Failure class for programmatic branching.
             * @example payment_failed
             */
            category: string;
        };
        /** @description Authentication error response (401) */
        AuthenticationError: {
            /** @example Invalid Credentials */
            detail: string;
            /** @example  */
            instance?: string;
            /** @example 401 */
            status: number;
            /** @example Authentication Required/Failed */
            title: string;
            /** @example https://api.terra-diagnostics.com/errors/authentication-error */
            type: string;
        };
        /** @description Confirmation that kit was activated successfully */
        ActivateKitResponse: {
            /** @example KIT123456789 */
            kit_id?: string;
            /** @example Kit activated successfully */
            message?: string;
            /** @example true */
            success?: boolean;
        };
        /** @description Current address of the test-taker (may differ from shipping address) */
        ActivationContextAddress: {
            /** @example 456 Oxford Street */
            address_line_1: string;
            /** @example Apt 7C */
            address_line_2?: string;
            /** @example Greater Manchester */
            administrative_area: string;
            /** @example Manchester */
            city: string;
            /**
             * @description ISO 3166-1 alpha-2 (e.g., "GB", "US")
             * @example GB
             */
            country_code: string;
            /** @example M1 5GD */
            postal_code: string;
        };
        /** @description Test-taker personal information (may differ from original recipient). The former country_code field was removed and is silently ignored if still sent. */
        ActivationContextRecipient: {
            /** @example 1985-03-20 */
            date_of_birth: string;
            /** @example john.smith@example.com */
            email: string;
            /** @example John */
            first_name?: string;
            /**
             * @example male
             * @enum {string}
             */
            gender_at_birth: "male" | "female";
            /** @example Smith */
            last_name?: string;
            /**
             * @description Required, in E.164 format: a leading "+", the country calling code, then the national number (e.g. "+447911123456"). A bare national number or a separate country_code is rejected.
             * @example +447911123456
             */
            phone_number: string;
        };
        /** @description Information provided by test-taker when activating their kit */
        ActivationContextDTO: {
            address: components["schemas"]["ActivationContextAddress"];
            /** @example 2025-11-15T09:00:00Z */
            collection_date?: string;
            recipient?: components["schemas"]["ActivationContextRecipient"];
            /** @example KIT123456789 */
            supplier_kit_id?: string;
        };
        /** @description Individual product variant and quantity in an order */
        OrderItemRequest: {
            /** @example 1 */
            quantity: number;
            /** @example 555666777 */
            variant_id: string;
        };
        /** @description Request body for creating a new diagnostic test order */
        CreateOrderRequest: {
            /**
             * @description Your unique order identifier that you generate, used for tracking and reconciliation. Not deduplicated server-side — retrying a create with the same value produces a second order.
             * @example ORDER-2024-001
             */
            client_order_reference_id: string;
            /**
             * @description Determines the required address field — shipping_address for AT_HOME, requested_lab_address for GO_TO_LAB.
             * @enum {string}
             */
            collection_type: "AT_HOME" | "GO_TO_LAB";
            /** @description Only need product_variant_id and quantity completely define what was ordered */
            items: components["schemas"]["OrderItemRequest"][];
            /** @description Details of the person who ordered. Depending on the supplier recipient is not necessarily the test-taker. Although some suppliers enforce this constraint on us. */
            recipient: components["schemas"]["RecipientRequestDTO"];
            requested_lab_address?: components["schemas"]["AddressDTO"];
            requested_lab?: components["schemas"]["RequestedLab"];
            shipping_address?: components["schemas"]["AddressDTO"];
        };
        /** @description Price breakdown including subtotal, tax, shipping, discounts */
        OrderFinancialDTO: {
            /**
             * @description @Description ISO 4217 format (e.g. 840 = USD)
             * @example 840
             */
            currency: number;
            /** @example 500 */
            discount_cents?: number;
            /** @example 10400 */
            total_cents: number;
        };
        /** @description Individual test kit or product in the order */
        OrderItemResponse: {
            /** @example 840 */
            currency: number;
            /** @example 2 */
            item_status?: number;
            /** @example LAB987654321 */
            lab_tracking_number?: string;
            /** @example 123456789 */
            order_id?: string;
            /** @example 987654321 */
            order_item_id?: string;
            /** @example 9990 */
            price_per_item_cents: number;
            /** @example 1 */
            product_type_id: string;
            /**
             * @description Test takers registered on this item (present once a kit is activated).
             * @example [
             *       "333410942627700738"
             *     ]
             */
            test_taker_ids?: string[];
            /**
             * @description Supplier-side item identifier (kit ID once assigned). Recoverable here even if the webhook that carried it was missed.
             * @example BXTWP00362
             */
            supplier_item_id?: string;
            /** @example 1 */
            quantity: number;
            /** @example results.awaiting_sample */
            results_status?: string;
            /** @example 555666777 */
            variant_id: string;
        };
        /** @description Response containing the created order details including tracking information */
        CreateOrderResponse: {
            /** @description For GO_TO_LAB orders: the bound draw site's address - the end user's selection when requested_lab was sent and verified, otherwise the nearest site to the requested lab address. Best-effort - null when resolution is unavailable; the requisition is typically accepted at any of the supplier network's sites. */
            confirmed_lab_address?: components["schemas"]["AddressDTO"];
            confirmed_lab?: components["schemas"]["ConfirmedLab"] | null;
            /** @example 2025-11-20 */
            estimated_delivery?: string;
            /** @example 123456789 */
            order_id: string;
            order_items?: components["schemas"]["OrderItemResponse"][];
            /**
             * @description Current fulfilment status in the REST `order.*` vocabulary. New orders start at `order.payment_processing`.
             * @example order.payment_processing
             */
            order_status?: string;
            /** @example 987654321 */
            recipient_id: string;
            /** @example TRK123456789GB */
            tracking_number?: string;
        };
        /** @description Full order information including items, recipient, address, and financials */
        GetOrderResponse: {
            /** @description Lifecycle timeline, newest first (order fulfilment + item results events). */
            status_history?: {
                /** @example order.processing */
                status: string;
                /** @example 333410942627700737 */
                order_item_id?: string;
                /** Format: date-time */
                changed_at: string;
                /**
                 * @description Present only on escalation_raised entries.
                 * @example high
                 */
                escalation_level?: string;
                /**
                 * Format: date-time
                 * @description Present only on escalation_raised entries.
                 */
                acknowledgment_due_by?: string;
            }[];
            /** @example terra_client_abc123 */
            client_id: string;
            /** @example ORDER-2024-001 */
            client_order_reference_id: string;
            /** @example AT_HOME */
            collection_type: string;
            confirmed_lab_address?: components["schemas"]["AddressDTO"];
            items: components["schemas"]["OrderItemResponse"][];
            order_financials: components["schemas"]["OrderFinancialDTO"];
            /** @example 123456789 */
            order_id: string;
            /**
             * @description Current fulfilment status in the REST `order.*` vocabulary.
             * @example order.delivery_fulfilled
             */
            order_status?: string;
            recipient: components["schemas"]["RecipientDTO"];
            requested_lab_address?: components["schemas"]["AddressDTO"];
            confirmed_lab?: components["schemas"]["ConfirmedLab"] | null;
            /** @description Echo of the selection sent at create time - lets a retrieval-only consumer tell "selected but unbound" from "no selection made". */
            requested_lab?: components["schemas"]["RequestedLab"];
            shipping_address: components["schemas"]["AddressDTO"];
        };
        /** @description GO_TO_LAB only: bind the order to a draw site chosen from GET /labs. code is the binding identity (row's code field); postal_code is a lookup hint (row's address.postal_code, ZIP+4 accepted - normalized to the 5-digit ZIP server-side; defaults to requested_lab_address.postal_code). Unknown codes are rejected with invalid_fields tag unknown_lab_code; if the lookup is temporarily unavailable the order is accepted unbound (confirmed_lab null). */
        RequestedLab: {
            /** @example T2O */
            code: string;
            /** @example 10001-6975 */
            postal_code?: string;
        };
        /** @description The draw site this order is bound to - a GET /labs row minus its request-relative distance field. Null when no binding exists (no selection and nearest-site resolution unavailable, or selection accepted unbound during a lookup outage). */
        ConfirmedLab: {
            /** @example T2O */
            code: string;
            /** @example Quest Diagnostics - NYC-26th St */
            name: string;
            address: components["schemas"]["AddressDTO"];
            /** @example 212-555-0100 */
            phone?: string;
            hours?: {
                [key: string]: string;
            };
            /** @example 40.7448 */
            latitude?: number;
            /** @example -73.9938 */
            longitude?: number;
            /** @example true */
            scheduling?: boolean;
        };
        /** @description Validation error when creating an order */
        CreateOrderValidationError: {
            /** @example One or more required fields are missing or invalid */
            detail: string;
            /** @example /api/v1/orders */
            instance: string;
            /** @example 400 */
            status: number;
            /** @example Validation Failed */
            title: string;
            /** @example https://api.terra-diagnostics.com/errors/validation-error */
            type: string;
            /** @description Per-field validation errors */
            invalid_fields?: {
                /** @example PhoneNumber */
                field?: string;
                /** @example country_code was removed; send phone_number in E.164 format: +447911123456 */
                message?: string;
                /** @example e164 */
                tag?: string;
                /** @example 07911123456 */
                value?: string;
            }[];
            /**
             * @description Present when the order was rejected for an unsupported country (tag unsupported_ship_to_country) - the ISO-3166 alpha-2 codes this test can be ordered in.
             * @example [
             *       "GB"
             *     ]
             */
            supported_ship_to_countries?: string[];
        };
        OrderStatusChangedEvent: {
            /** @constant */
            event_type: "order.status_changed";
            /**
             * @description Unique per event (64-bit id serialized as a string) — deduplicate on this. Equals the X-Terra-Trace-Id header.
             * @example 249956485092777984
             */
            event_id: string;
            /**
             * @description Unix seconds when the event was sent.
             * @example 1763661470
             */
            timestamp: number;
            data: {
                /** @example 333410942627700736 */
                order_id: string;
                /** @enum {string} */
                status: "order.payment_processing" | "order.payment_complete" | "order.payment_failed" | "order.processing" | "order.delayed" | "order.cancelled" | "order.completed" | "order.delivery_fulfilled";
                /**
                 * @description Present once delivery details are available.
                 * @example KnD3d5PMZyq5ulNcWkrq
                 */
                tracking_number?: string;
                /**
                 * @description Sandbox payloads only — the supplier-side kit ID.
                 * @example 249602021676720128
                 */
                supplier_item_id?: string;
            };
        };
        OrderItemResultsStatusChangedEvent: {
            /** @constant */
            event_type: "order_item.results_status_change";
            /**
             * @description Unique per event (64-bit id serialized as a string) — deduplicate on this. Equals the X-Terra-Trace-Id header.
             * @example 249958796259139584
             */
            event_id: string;
            /**
             * @description Unix seconds when the event was sent.
             * @example 1763662021
             */
            timestamp: number;
            data: {
                /** @example 333410942627700736 */
                order_id: string;
                /** @example 333410942627700737 */
                order_item_id: string;
                /** @example 100011 */
                variant_id: string;
                /** @enum {string} */
                results_status: "results.kit_activated" | "results.sample_processing_in_lab" | "results.sample_rejected" | "results.partial_results_ready" | "results.results_ready" | "results.lab_processing_error" | "results.escalation_raised";
                test_taker: {
                    /** @example 333410942627700738 */
                    test_taker_id: string;
                    first_name: string;
                    last_name: string;
                    email: string;
                    /**
                     * @description E.164 phone number
                     * @example +447911123456
                     */
                    phone_number: string;
                };
                /**
                 * @description Present on escalation_raised.
                 * @enum {string}
                 */
                escalation_level?: "not_escalated" | "very_low" | "low" | "medium" | "high" | "very_high";
                /**
                 * @description Present on escalation_raised — ISO 8601 deadline.
                 * @example 2026-07-24T16:04:01Z
                 */
                acknowledgment_due_by?: string;
                /**
                 * @description Present on sample_rejected.
                 * @example blood contaminated
                 */
                failure_cause?: string;
            };
        };
        /** @description Response containing a presigned URL to download test results */
        GetResultsURLResponse: {
            /** @example https://storage.googleapis.com/bucket/results/123.json?signature=abc123 */
            download_url?: string;
            /** @example 2025-10-23T18:00:00Z */
            expires_at?: string;
            /**
             * @example json
             * @enum {string}
             */
            format?: "json";
        };
        /** @description Confirmation that results were acknowledged */
        AcknowledgeResultsResponse: {
            /** @example acknowledged */
            status?: string;
        };
        /**
         * Format: int32
         * @enum {integer}
         */
        AvailabilityStatus: 0 | 1 | 2;
        /**
         * Format: int32
         * @enum {integer}
         */
        Currency: 0 | 840 | 978 | 826;
        Image: {
            alt_text?: string;
            /** Format: int32 */
            display_order?: number;
            /** Format: int32 */
            height?: number;
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            product_id?: number;
            url?: string;
            /** Format: int64 */
            variant_id?: number;
            /** Format: int32 */
            width?: number;
        };
        ProductVariant: {
            available_collection_types?: string[];
            /**
             * @description ISO-3166 alpha-2 codes this test can be ordered in (AT_HOME shipping destination; for GO_TO_LAB, the requested lab country). Gate your address form on it - orders outside these countries are rejected with an unsupported_ship_to_country field error.
             * @example [
             *       "GB"
             *     ]
             */
            supported_ship_to_countries?: string[];
            /** Format: int32 */
            currency?: number;
            descriptive_attrs_override?: {
                [key: string]: unknown;
            };
            /** Format: int64 */
            id?: number;
            images?: components["schemas"]["Image"][];
            /** Format: int32 */
            price_cents?: number;
            /** Format: int64 */
            product_id?: number;
            /** Format: int64 */
            product_type_id?: number;
            /** Format: int32 */
            variant_availability?: number;
            variant_defining_attrs?: {
                [key: string]: unknown;
            };
            variant_name?: string;
        };
        Product: {
            /** @description Present only on ?show_all=true — the caller's per-product curation flag. */
            enabled?: boolean;
            availability?: components["schemas"]["AvailabilityStatus"];
            /** Format: int32 */
            base_price_cents?: number;
            currency?: components["schemas"]["Currency"];
            description?: string;
            /** Format: int64 */
            id?: number;
            images?: components["schemas"]["Image"][];
            model_descriptive_attrs?: {
                [key: string]: string;
            };
            name?: string;
            /** Format: int64 */
            product_type_id?: number;
            variants?: components["schemas"]["ProductVariant"][];
        };
        ProductType: {
            description?: string;
            /** Format: int64 */
            id?: number;
            name?: string;
        };
        ListLabsResponse: {
            labs: components["schemas"]["PSCLocation"][];
        };
        /** @description A Patient Service Center (lab draw site). */
        PSCLocation: {
            /** @example PSC12345 */
            code: string;
            /** @example Quest Diagnostics - Midtown */
            name: string;
            address: components["schemas"]["AddressDTO"];
            /** @example +1-212-555-0100 */
            phone: string;
            /**
             * @description Opening hours keyed by weekday.
             * @example {
             *       "monday": "08:00-17:00"
             *     }
             */
            hours?: {
                [key: string]: string;
            };
            /** @example 40.7549 */
            latitude: number;
            /** @example -73.984 */
            longitude: number;
            /** @description Whether online scheduling is open. */
            scheduling: boolean;
            /** @description Miles from the requested zip. */
            distance: number;
        };
        OverviewResponse: {
            orders: {
                /** @example 27 */
                total: number;
                /**
                 * @description Order counts keyed by current fulfilment status string.
                 * @example {
                 *       "order.completed": 29,
                 *       "order.processing": 8
                 *     }
                 */
                by_status: {
                    [key: string]: number;
                };
            };
            results: {
                /** @example 7 */
                total: number;
                /** @example 8 */
                missing: number;
            };
            webhooks: {
                /** @example 5 */
                failed_total: number;
                daily: {
                    /** @example 2026-05-16 */
                    date: string;
                    /** @example 1 */
                    failed: number;
                }[];
            };
        };
        WebhookDeliveriesResponse: {
            deliveries: components["schemas"]["WebhookDelivery"][];
            /**
             * @description Pass as ?cursor= for the next page; absent on the last page.
             * @example 333410942627700737
             */
            next_cursor?: string;
        };
        WebhookDelivery: {
            /** @example 333410942627700737 */
            event_id: string;
            /**
             * @description Same vocabulary as the webhook event_type field (currently order.status_changed, order_item.status_changed and order_item.results_status_change). Open set - new event types may appear; treat unknown values as deliveries of a newer event family.
             * @example order_item.results_status_change
             */
            event_type: string;
            /** @example 333410942627700736 */
            order_id: string;
            /** @example 333410942627700737 */
            order_item_id: string;
            /**
             * @description One of: delivered, rejected, invalid, dead_lettered, replayed.
             * @example dead_lettered
             */
            outcome: string;
            /** @example 500 */
            final_status_code: number | null;
            /** @example 6 */
            attempts: number;
            /** Format: date-time */
            completed_at: string;
            /** Format: date-time */
            event_created_at: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    webhookOrderStatusChanged: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderStatusChangedEvent"];
            };
        };
        responses: {
            /** @description Return any 2xx quickly to acknowledge receipt. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    webhookOrderItemResultsStatusChange: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderItemResultsStatusChangedEvent"];
            };
        };
        responses: {
            /** @description Return any 2xx quickly to acknowledge receipt. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
