/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OpsRouteRouteImport } from './routes/ops/route'
import { Route as ShopRouteRouteImport } from './routes/shop/route'
import { Route as OpsIndexRouteImport } from './routes/ops/index'
import { Route as OpsCatalogRouteImport } from './routes/ops/catalog'
import { Route as OpsOrdersRouteImport } from './routes/ops/orders'
import { Route as OpsResultsRouteImport } from './routes/ops/results'
import { Route as OpsWebhooksRouteImport } from './routes/ops/webhooks'
import { Route as ShopIndexRouteImport } from './routes/shop/index'
import { Route as ShopKitsRouteImport } from './routes/shop/kits'
import { Route as ShopOrderRouteImport } from './routes/shop/order'
import { Route as OpsOrdersOrderIdRouteImport } from './routes/ops/orders.$orderId'
import { Route as ShopKitsOrderItemIdRouteImport } from './routes/shop/kits.$orderItemId'
import { Route as ShopKitsOrderItemIdResultRouteImport } from './routes/shop/kits.$orderItemId.result'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsRouteRoute = OpsRouteRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRouteRoute = ShopRouteRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsIndexRoute = OpsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OpsRouteRoute,
} as any)
const OpsCatalogRoute = OpsCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => OpsRouteRoute,
} as any)
const OpsOrdersRoute = OpsOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => OpsRouteRoute,
} as any)
const OpsResultsRoute = OpsResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => OpsRouteRoute,
} as any)
const OpsWebhooksRoute = OpsWebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => OpsRouteRoute,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShopRouteRoute,
} as any)
const ShopKitsRoute = ShopKitsRouteImport.update({
  id: '/kits',
  path: '/kits',
  getParentRoute: () => ShopRouteRoute,
} as any)
const ShopOrderRoute = ShopOrderRouteImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => ShopRouteRoute,
} as any)
const OpsOrdersOrderIdRoute = OpsOrdersOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => OpsOrdersRoute,
} as any)
const ShopKitsOrderItemIdRoute = ShopKitsOrderItemIdRouteImport.update({
  id: '/$orderItemId',
  path: '/$orderItemId',
  getParentRoute: () => ShopKitsRoute,
} as any)
const ShopKitsOrderItemIdResultRoute =
  ShopKitsOrderItemIdResultRouteImport.update({
    id: '/result',
    path: '/result',
    getParentRoute: () => ShopKitsOrderItemIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ops': typeof OpsRouteRouteWithChildren
  '/shop': typeof ShopRouteRouteWithChildren
  '/ops/catalog': typeof OpsCatalogRoute
  '/ops/orders': typeof OpsOrdersRouteWithChildren
  '/ops/results': typeof OpsResultsRoute
  '/ops/webhooks': typeof OpsWebhooksRoute
  '/shop/kits': typeof ShopKitsRouteWithChildren
  '/shop/order': typeof ShopOrderRoute
  '/ops/': typeof OpsIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/ops/orders/$orderId': typeof OpsOrdersOrderIdRoute
  '/shop/kits/$orderItemId': typeof ShopKitsOrderItemIdRouteWithChildren
  '/shop/kits/$orderItemId/result': typeof ShopKitsOrderItemIdResultRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ops/catalog': typeof OpsCatalogRoute
  '/ops/orders': typeof OpsOrdersRouteWithChildren
  '/ops/results': typeof OpsResultsRoute
  '/ops/webhooks': typeof OpsWebhooksRoute
  '/shop/kits': typeof ShopKitsRouteWithChildren
  '/shop/order': typeof ShopOrderRoute
  '/ops': typeof OpsIndexRoute
  '/shop': typeof ShopIndexRoute
  '/ops/orders/$orderId': typeof OpsOrdersOrderIdRoute
  '/shop/kits/$orderItemId': typeof ShopKitsOrderItemIdRouteWithChildren
  '/shop/kits/$orderItemId/result': typeof ShopKitsOrderItemIdResultRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ops': typeof OpsRouteRouteWithChildren
  '/shop': typeof ShopRouteRouteWithChildren
  '/ops/catalog': typeof OpsCatalogRoute
  '/ops/orders': typeof OpsOrdersRouteWithChildren
  '/ops/results': typeof OpsResultsRoute
  '/ops/webhooks': typeof OpsWebhooksRoute
  '/shop/kits': typeof ShopKitsRouteWithChildren
  '/shop/order': typeof ShopOrderRoute
  '/ops/': typeof OpsIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/ops/orders/$orderId': typeof OpsOrdersOrderIdRoute
  '/shop/kits/$orderItemId': typeof ShopKitsOrderItemIdRouteWithChildren
  '/shop/kits/$orderItemId/result': typeof ShopKitsOrderItemIdResultRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ops'
    | '/shop'
    | '/ops/catalog'
    | '/ops/orders'
    | '/ops/results'
    | '/ops/webhooks'
    | '/shop/kits'
    | '/shop/order'
    | '/ops/'
    | '/shop/'
    | '/ops/orders/$orderId'
    | '/shop/kits/$orderItemId'
    | '/shop/kits/$orderItemId/result'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ops/catalog'
    | '/ops/orders'
    | '/ops/results'
    | '/ops/webhooks'
    | '/shop/kits'
    | '/shop/order'
    | '/ops'
    | '/shop'
    | '/ops/orders/$orderId'
    | '/shop/kits/$orderItemId'
    | '/shop/kits/$orderItemId/result'
  id:
    | '__root__'
    | '/'
    | '/ops'
    | '/shop'
    | '/ops/catalog'
    | '/ops/orders'
    | '/ops/results'
    | '/ops/webhooks'
    | '/shop/kits'
    | '/shop/order'
    | '/ops/'
    | '/shop/'
    | '/ops/orders/$orderId'
    | '/shop/kits/$orderItemId'
    | '/shop/kits/$orderItemId/result'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OpsRouteRoute: typeof OpsRouteRouteWithChildren
  ShopRouteRoute: typeof ShopRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops': {
      id: '/ops'
      path: '/ops'
      fullPath: '/ops'
      preLoaderRoute: typeof OpsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops/': {
      id: '/ops/'
      path: '/'
      fullPath: '/ops/'
      preLoaderRoute: typeof OpsIndexRouteImport
      parentRoute: typeof OpsRouteRoute
    }
    '/ops/catalog': {
      id: '/ops/catalog'
      path: '/catalog'
      fullPath: '/ops/catalog'
      preLoaderRoute: typeof OpsCatalogRouteImport
      parentRoute: typeof OpsRouteRoute
    }
    '/ops/orders': {
      id: '/ops/orders'
      path: '/orders'
      fullPath: '/ops/orders'
      preLoaderRoute: typeof OpsOrdersRouteImport
      parentRoute: typeof OpsRouteRoute
    }
    '/ops/results': {
      id: '/ops/results'
      path: '/results'
      fullPath: '/ops/results'
      preLoaderRoute: typeof OpsResultsRouteImport
      parentRoute: typeof OpsRouteRoute
    }
    '/ops/webhooks': {
      id: '/ops/webhooks'
      path: '/webhooks'
      fullPath: '/ops/webhooks'
      preLoaderRoute: typeof OpsWebhooksRouteImport
      parentRoute: typeof OpsRouteRoute
    }
    '/shop/': {
      id: '/shop/'
      path: '/'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof ShopRouteRoute
    }
    '/shop/kits': {
      id: '/shop/kits'
      path: '/kits'
      fullPath: '/shop/kits'
      preLoaderRoute: typeof ShopKitsRouteImport
      parentRoute: typeof ShopRouteRoute
    }
    '/shop/order': {
      id: '/shop/order'
      path: '/order'
      fullPath: '/shop/order'
      preLoaderRoute: typeof ShopOrderRouteImport
      parentRoute: typeof ShopRouteRoute
    }
    '/ops/orders/$orderId': {
      id: '/ops/orders/$orderId'
      path: '/$orderId'
      fullPath: '/ops/orders/$orderId'
      preLoaderRoute: typeof OpsOrdersOrderIdRouteImport
      parentRoute: typeof OpsOrdersRoute
    }
    '/shop/kits/$orderItemId': {
      id: '/shop/kits/$orderItemId'
      path: '/$orderItemId'
      fullPath: '/shop/kits/$orderItemId'
      preLoaderRoute: typeof ShopKitsOrderItemIdRouteImport
      parentRoute: typeof ShopKitsRoute
    }
    '/shop/kits/$orderItemId/result': {
      id: '/shop/kits/$orderItemId/result'
      path: '/result'
      fullPath: '/shop/kits/$orderItemId/result'
      preLoaderRoute: typeof ShopKitsOrderItemIdResultRouteImport
      parentRoute: typeof ShopKitsOrderItemIdRoute
    }
  }
}

interface OpsOrdersRouteChildren {
  OpsOrdersOrderIdRoute: typeof OpsOrdersOrderIdRoute
}

const OpsOrdersRouteChildren: OpsOrdersRouteChildren = {
  OpsOrdersOrderIdRoute: OpsOrdersOrderIdRoute,
}

const OpsOrdersRouteWithChildren = OpsOrdersRoute._addFileChildren(
  OpsOrdersRouteChildren,
)

interface OpsRouteRouteChildren {
  OpsCatalogRoute: typeof OpsCatalogRoute
  OpsOrdersRoute: typeof OpsOrdersRouteWithChildren
  OpsResultsRoute: typeof OpsResultsRoute
  OpsWebhooksRoute: typeof OpsWebhooksRoute
  OpsIndexRoute: typeof OpsIndexRoute
}

const OpsRouteRouteChildren: OpsRouteRouteChildren = {
  OpsCatalogRoute: OpsCatalogRoute,
  OpsOrdersRoute: OpsOrdersRouteWithChildren,
  OpsResultsRoute: OpsResultsRoute,
  OpsWebhooksRoute: OpsWebhooksRoute,
  OpsIndexRoute: OpsIndexRoute,
}

const OpsRouteRouteWithChildren = OpsRouteRoute._addFileChildren(
  OpsRouteRouteChildren,
)

interface ShopKitsOrderItemIdRouteChildren {
  ShopKitsOrderItemIdResultRoute: typeof ShopKitsOrderItemIdResultRoute
}

const ShopKitsOrderItemIdRouteChildren: ShopKitsOrderItemIdRouteChildren = {
  ShopKitsOrderItemIdResultRoute: ShopKitsOrderItemIdResultRoute,
}

const ShopKitsOrderItemIdRouteWithChildren =
  ShopKitsOrderItemIdRoute._addFileChildren(ShopKitsOrderItemIdRouteChildren)

interface ShopKitsRouteChildren {
  ShopKitsOrderItemIdRoute: typeof ShopKitsOrderItemIdRouteWithChildren
}

const ShopKitsRouteChildren: ShopKitsRouteChildren = {
  ShopKitsOrderItemIdRoute: ShopKitsOrderItemIdRouteWithChildren,
}

const ShopKitsRouteWithChildren = ShopKitsRoute._addFileChildren(
  ShopKitsRouteChildren,
)

interface ShopRouteRouteChildren {
  ShopKitsRoute: typeof ShopKitsRouteWithChildren
  ShopOrderRoute: typeof ShopOrderRoute
  ShopIndexRoute: typeof ShopIndexRoute
}

const ShopRouteRouteChildren: ShopRouteRouteChildren = {
  ShopKitsRoute: ShopKitsRouteWithChildren,
  ShopOrderRoute: ShopOrderRoute,
  ShopIndexRoute: ShopIndexRoute,
}

const ShopRouteRouteWithChildren = ShopRouteRoute._addFileChildren(
  ShopRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OpsRouteRoute: OpsRouteRouteWithChildren,
  ShopRouteRoute: ShopRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
