/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicVerifyRouteRouteImport } from './routes/_public/verify/route'
import { Route as PublicRegisterRouteRouteImport } from './routes/_public/register/route'
import { Route as PublicLoginRouteRouteImport } from './routes/_public/login/route'
import { Route as AuthenticatedTrendsRouteRouteImport } from './routes/_authenticated/trends/route'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedDashboardRouteRouteImport } from './routes/_authenticated/dashboard/route'
import { Route as AuthenticatedConnectorsRouteRouteImport } from './routes/_authenticated/connectors/route'
import { Route as AuthenticatedChatRouteRouteImport } from './routes/_authenticated/chat/route'
import { Route as AuthenticatedTrendsIndexRouteImport } from './routes/_authenticated/trends/index'
import { Route as AuthenticatedConnectorsIndexRouteImport } from './routes/_authenticated/connectors/index'
import { Route as AuthenticatedChatIndexRouteImport } from './routes/_authenticated/chat/index'
import { Route as AuthenticatedTrendsMetricRouteImport } from './routes/_authenticated/trends/$metric'
import { Route as AuthenticatedConnectorsConnectionIdRouteImport } from './routes/_authenticated/connectors/$connectionId'
import { Route as AuthenticatedChatNewRouteImport } from './routes/_authenticated/chat/new'
import { Route as AuthenticatedChatChatIdRouteImport } from './routes/_authenticated/chat/$chatId'
import { Route as AuthenticatedOnboardingProfileRouteRouteImport } from './routes/_authenticated/onboarding/profile/route'
import { Route as AuthenticatedOnboardingConnectRouteRouteImport } from './routes/_authenticated/onboarding/connect/route'

const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicVerifyRouteRoute = PublicVerifyRouteRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicRegisterRouteRoute = PublicRegisterRouteRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicLoginRouteRoute = PublicLoginRouteRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AuthenticatedTrendsRouteRoute =
  AuthenticatedTrendsRouteRouteImport.update({
    id: '/trends',
    path: '/trends',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRouteRoute =
  AuthenticatedDashboardRouteRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConnectorsRouteRoute =
  AuthenticatedConnectorsRouteRouteImport.update({
    id: '/connectors',
    path: '/connectors',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatRouteRoute = AuthenticatedChatRouteRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTrendsIndexRoute =
  AuthenticatedTrendsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedTrendsRouteRoute,
  } as any)
const AuthenticatedConnectorsIndexRoute =
  AuthenticatedConnectorsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedConnectorsRouteRoute,
  } as any)
const AuthenticatedChatIndexRoute = AuthenticatedChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedChatRouteRoute,
} as any)
const AuthenticatedTrendsMetricRoute =
  AuthenticatedTrendsMetricRouteImport.update({
    id: '/$metric',
    path: '/$metric',
    getParentRoute: () => AuthenticatedTrendsRouteRoute,
  } as any)
const AuthenticatedConnectorsConnectionIdRoute =
  AuthenticatedConnectorsConnectionIdRouteImport.update({
    id: '/$connectionId',
    path: '/$connectionId',
    getParentRoute: () => AuthenticatedConnectorsRouteRoute,
  } as any)
const AuthenticatedChatNewRoute = AuthenticatedChatNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedChatRouteRoute,
} as any)
const AuthenticatedChatChatIdRoute = AuthenticatedChatChatIdRouteImport.update({
  id: '/$chatId',
  path: '/$chatId',
  getParentRoute: () => AuthenticatedChatRouteRoute,
} as any)
const AuthenticatedOnboardingProfileRouteRoute =
  AuthenticatedOnboardingProfileRouteRouteImport.update({
    id: '/onboarding/profile',
    path: '/onboarding/profile',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingConnectRouteRoute =
  AuthenticatedOnboardingConnectRouteRouteImport.update({
    id: '/onboarding/connect',
    path: '/onboarding/connect',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/chat': typeof AuthenticatedChatRouteRouteWithChildren
  '/connectors': typeof AuthenticatedConnectorsRouteRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRouteRoute
  '/settings': typeof AuthenticatedSettingsRouteRoute
  '/trends': typeof AuthenticatedTrendsRouteRouteWithChildren
  '/login': typeof PublicLoginRouteRoute
  '/register': typeof PublicRegisterRouteRoute
  '/verify': typeof PublicVerifyRouteRoute
  '/onboarding/connect': typeof AuthenticatedOnboardingConnectRouteRoute
  '/onboarding/profile': typeof AuthenticatedOnboardingProfileRouteRoute
  '/chat/$chatId': typeof AuthenticatedChatChatIdRoute
  '/chat/new': typeof AuthenticatedChatNewRoute
  '/connectors/$connectionId': typeof AuthenticatedConnectorsConnectionIdRoute
  '/trends/$metric': typeof AuthenticatedTrendsMetricRoute
  '/chat/': typeof AuthenticatedChatIndexRoute
  '/connectors/': typeof AuthenticatedConnectorsIndexRoute
  '/trends/': typeof AuthenticatedTrendsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/dashboard': typeof AuthenticatedDashboardRouteRoute
  '/settings': typeof AuthenticatedSettingsRouteRoute
  '/login': typeof PublicLoginRouteRoute
  '/register': typeof PublicRegisterRouteRoute
  '/verify': typeof PublicVerifyRouteRoute
  '/onboarding/connect': typeof AuthenticatedOnboardingConnectRouteRoute
  '/onboarding/profile': typeof AuthenticatedOnboardingProfileRouteRoute
  '/chat/$chatId': typeof AuthenticatedChatChatIdRoute
  '/chat/new': typeof AuthenticatedChatNewRoute
  '/connectors/$connectionId': typeof AuthenticatedConnectorsConnectionIdRoute
  '/trends/$metric': typeof AuthenticatedTrendsMetricRoute
  '/chat': typeof AuthenticatedChatIndexRoute
  '/connectors': typeof AuthenticatedConnectorsIndexRoute
  '/trends': typeof AuthenticatedTrendsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/_authenticated/chat': typeof AuthenticatedChatRouteRouteWithChildren
  '/_authenticated/connectors': typeof AuthenticatedConnectorsRouteRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRoute
  '/_authenticated/trends': typeof AuthenticatedTrendsRouteRouteWithChildren
  '/_public/login': typeof PublicLoginRouteRoute
  '/_public/register': typeof PublicRegisterRouteRoute
  '/_public/verify': typeof PublicVerifyRouteRoute
  '/_public/': typeof PublicIndexRoute
  '/_authenticated/onboarding/connect': typeof AuthenticatedOnboardingConnectRouteRoute
  '/_authenticated/onboarding/profile': typeof AuthenticatedOnboardingProfileRouteRoute
  '/_authenticated/chat/$chatId': typeof AuthenticatedChatChatIdRoute
  '/_authenticated/chat/new': typeof AuthenticatedChatNewRoute
  '/_authenticated/connectors/$connectionId': typeof AuthenticatedConnectorsConnectionIdRoute
  '/_authenticated/trends/$metric': typeof AuthenticatedTrendsMetricRoute
  '/_authenticated/chat/': typeof AuthenticatedChatIndexRoute
  '/_authenticated/connectors/': typeof AuthenticatedConnectorsIndexRoute
  '/_authenticated/trends/': typeof AuthenticatedTrendsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/connectors'
    | '/dashboard'
    | '/settings'
    | '/trends'
    | '/login'
    | '/register'
    | '/verify'
    | '/onboarding/connect'
    | '/onboarding/profile'
    | '/chat/$chatId'
    | '/chat/new'
    | '/connectors/$connectionId'
    | '/trends/$metric'
    | '/chat/'
    | '/connectors/'
    | '/trends/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/settings'
    | '/login'
    | '/register'
    | '/verify'
    | '/onboarding/connect'
    | '/onboarding/profile'
    | '/chat/$chatId'
    | '/chat/new'
    | '/connectors/$connectionId'
    | '/trends/$metric'
    | '/chat'
    | '/connectors'
    | '/trends'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_public'
    | '/_authenticated/chat'
    | '/_authenticated/connectors'
    | '/_authenticated/dashboard'
    | '/_authenticated/settings'
    | '/_authenticated/trends'
    | '/_public/login'
    | '/_public/register'
    | '/_public/verify'
    | '/_public/'
    | '/_authenticated/onboarding/connect'
    | '/_authenticated/onboarding/profile'
    | '/_authenticated/chat/$chatId'
    | '/_authenticated/chat/new'
    | '/_authenticated/connectors/$connectionId'
    | '/_authenticated/trends/$metric'
    | '/_authenticated/chat/'
    | '/_authenticated/connectors/'
    | '/_authenticated/trends/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/verify': {
      id: '/_public/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof PublicVerifyRouteRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/register': {
      id: '/_public/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof PublicRegisterRouteRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_authenticated/trends': {
      id: '/_authenticated/trends'
      path: '/trends'
      fullPath: '/trends'
      preLoaderRoute: typeof AuthenticatedTrendsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/connectors': {
      id: '/_authenticated/connectors'
      path: '/connectors'
      fullPath: '/connectors'
      preLoaderRoute: typeof AuthenticatedConnectorsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trends/': {
      id: '/_authenticated/trends/'
      path: '/'
      fullPath: '/trends/'
      preLoaderRoute: typeof AuthenticatedTrendsIndexRouteImport
      parentRoute: typeof AuthenticatedTrendsRouteRoute
    }
    '/_authenticated/connectors/': {
      id: '/_authenticated/connectors/'
      path: '/'
      fullPath: '/connectors/'
      preLoaderRoute: typeof AuthenticatedConnectorsIndexRouteImport
      parentRoute: typeof AuthenticatedConnectorsRouteRoute
    }
    '/_authenticated/chat/': {
      id: '/_authenticated/chat/'
      path: '/'
      fullPath: '/chat/'
      preLoaderRoute: typeof AuthenticatedChatIndexRouteImport
      parentRoute: typeof AuthenticatedChatRouteRoute
    }
    '/_authenticated/trends/$metric': {
      id: '/_authenticated/trends/$metric'
      path: '/$metric'
      fullPath: '/trends/$metric'
      preLoaderRoute: typeof AuthenticatedTrendsMetricRouteImport
      parentRoute: typeof AuthenticatedTrendsRouteRoute
    }
    '/_authenticated/connectors/$connectionId': {
      id: '/_authenticated/connectors/$connectionId'
      path: '/$connectionId'
      fullPath: '/connectors/$connectionId'
      preLoaderRoute: typeof AuthenticatedConnectorsConnectionIdRouteImport
      parentRoute: typeof AuthenticatedConnectorsRouteRoute
    }
    '/_authenticated/chat/new': {
      id: '/_authenticated/chat/new'
      path: '/new'
      fullPath: '/chat/new'
      preLoaderRoute: typeof AuthenticatedChatNewRouteImport
      parentRoute: typeof AuthenticatedChatRouteRoute
    }
    '/_authenticated/chat/$chatId': {
      id: '/_authenticated/chat/$chatId'
      path: '/$chatId'
      fullPath: '/chat/$chatId'
      preLoaderRoute: typeof AuthenticatedChatChatIdRouteImport
      parentRoute: typeof AuthenticatedChatRouteRoute
    }
    '/_authenticated/onboarding/profile': {
      id: '/_authenticated/onboarding/profile'
      path: '/onboarding/profile'
      fullPath: '/onboarding/profile'
      preLoaderRoute: typeof AuthenticatedOnboardingProfileRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding/connect': {
      id: '/_authenticated/onboarding/connect'
      path: '/onboarding/connect'
      fullPath: '/onboarding/connect'
      preLoaderRoute: typeof AuthenticatedOnboardingConnectRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedChatRouteRouteChildren {
  AuthenticatedChatChatIdRoute: typeof AuthenticatedChatChatIdRoute
  AuthenticatedChatNewRoute: typeof AuthenticatedChatNewRoute
  AuthenticatedChatIndexRoute: typeof AuthenticatedChatIndexRoute
}

const AuthenticatedChatRouteRouteChildren: AuthenticatedChatRouteRouteChildren =
  {
    AuthenticatedChatChatIdRoute: AuthenticatedChatChatIdRoute,
    AuthenticatedChatNewRoute: AuthenticatedChatNewRoute,
    AuthenticatedChatIndexRoute: AuthenticatedChatIndexRoute,
  }

const AuthenticatedChatRouteRouteWithChildren =
  AuthenticatedChatRouteRoute._addFileChildren(
    AuthenticatedChatRouteRouteChildren,
  )

interface AuthenticatedConnectorsRouteRouteChildren {
  AuthenticatedConnectorsConnectionIdRoute: typeof AuthenticatedConnectorsConnectionIdRoute
  AuthenticatedConnectorsIndexRoute: typeof AuthenticatedConnectorsIndexRoute
}

const AuthenticatedConnectorsRouteRouteChildren: AuthenticatedConnectorsRouteRouteChildren =
  {
    AuthenticatedConnectorsConnectionIdRoute:
      AuthenticatedConnectorsConnectionIdRoute,
    AuthenticatedConnectorsIndexRoute: AuthenticatedConnectorsIndexRoute,
  }

const AuthenticatedConnectorsRouteRouteWithChildren =
  AuthenticatedConnectorsRouteRoute._addFileChildren(
    AuthenticatedConnectorsRouteRouteChildren,
  )

interface AuthenticatedTrendsRouteRouteChildren {
  AuthenticatedTrendsMetricRoute: typeof AuthenticatedTrendsMetricRoute
  AuthenticatedTrendsIndexRoute: typeof AuthenticatedTrendsIndexRoute
}

const AuthenticatedTrendsRouteRouteChildren: AuthenticatedTrendsRouteRouteChildren =
  {
    AuthenticatedTrendsMetricRoute: AuthenticatedTrendsMetricRoute,
    AuthenticatedTrendsIndexRoute: AuthenticatedTrendsIndexRoute,
  }

const AuthenticatedTrendsRouteRouteWithChildren =
  AuthenticatedTrendsRouteRoute._addFileChildren(
    AuthenticatedTrendsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedChatRouteRoute: typeof AuthenticatedChatRouteRouteWithChildren
  AuthenticatedConnectorsRouteRoute: typeof AuthenticatedConnectorsRouteRouteWithChildren
  AuthenticatedDashboardRouteRoute: typeof AuthenticatedDashboardRouteRoute
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRoute
  AuthenticatedTrendsRouteRoute: typeof AuthenticatedTrendsRouteRouteWithChildren
  AuthenticatedOnboardingConnectRouteRoute: typeof AuthenticatedOnboardingConnectRouteRoute
  AuthenticatedOnboardingProfileRouteRoute: typeof AuthenticatedOnboardingProfileRouteRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedChatRouteRoute: AuthenticatedChatRouteRouteWithChildren,
  AuthenticatedConnectorsRouteRoute:
    AuthenticatedConnectorsRouteRouteWithChildren,
  AuthenticatedDashboardRouteRoute: AuthenticatedDashboardRouteRoute,
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRoute,
  AuthenticatedTrendsRouteRoute: AuthenticatedTrendsRouteRouteWithChildren,
  AuthenticatedOnboardingConnectRouteRoute:
    AuthenticatedOnboardingConnectRouteRoute,
  AuthenticatedOnboardingProfileRouteRoute:
    AuthenticatedOnboardingProfileRouteRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface PublicRouteRouteChildren {
  PublicLoginRouteRoute: typeof PublicLoginRouteRoute
  PublicRegisterRouteRoute: typeof PublicRegisterRouteRoute
  PublicVerifyRouteRoute: typeof PublicVerifyRouteRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicLoginRouteRoute: PublicLoginRouteRoute,
  PublicRegisterRouteRoute: PublicRegisterRouteRoute,
  PublicVerifyRouteRoute: PublicVerifyRouteRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
