/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PatientsIndexRouteImport } from './routes/patients/index'
import { Route as PatientsPatientIdRouteRouteImport } from './routes/patients/$patientId/route'
import { Route as PatientsPatientIdIndexRouteImport } from './routes/patients/$patientId/index'
import { Route as PatientsPatientIdLabTrendsRouteImport } from './routes/patients/$patientId/lab-trends'
import { Route as PatientsPatientIdUploadRouteImport } from './routes/patients/$patientId/upload'
import { Route as PatientsPatientIdWearablesRouteImport } from './routes/patients/$patientId/wearables'
import { Route as PatientsPatientIdDomainsDomainKeyRouteImport } from './routes/patients/$patientId/domains.$domainKey'
import { Route as PatientsPatientIdReportsSessionIdRouteImport } from './routes/patients/$patientId/reports.$sessionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsIndexRoute = PatientsIndexRouteImport.update({
  id: '/patients/',
  path: '/patients/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsPatientIdRouteRoute = PatientsPatientIdRouteRouteImport.update({
  id: '/patients/$patientId',
  path: '/patients/$patientId',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsPatientIdIndexRoute = PatientsPatientIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PatientsPatientIdRouteRoute,
} as any)
const PatientsPatientIdLabTrendsRoute =
  PatientsPatientIdLabTrendsRouteImport.update({
    id: '/lab-trends',
    path: '/lab-trends',
    getParentRoute: () => PatientsPatientIdRouteRoute,
  } as any)
const PatientsPatientIdUploadRoute = PatientsPatientIdUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => PatientsPatientIdRouteRoute,
} as any)
const PatientsPatientIdWearablesRoute =
  PatientsPatientIdWearablesRouteImport.update({
    id: '/wearables',
    path: '/wearables',
    getParentRoute: () => PatientsPatientIdRouteRoute,
  } as any)
const PatientsPatientIdDomainsDomainKeyRoute =
  PatientsPatientIdDomainsDomainKeyRouteImport.update({
    id: '/domains/$domainKey',
    path: '/domains/$domainKey',
    getParentRoute: () => PatientsPatientIdRouteRoute,
  } as any)
const PatientsPatientIdReportsSessionIdRoute =
  PatientsPatientIdReportsSessionIdRouteImport.update({
    id: '/reports/$sessionId',
    path: '/reports/$sessionId',
    getParentRoute: () => PatientsPatientIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/patients/$patientId': typeof PatientsPatientIdRouteRouteWithChildren
  '/patients/': typeof PatientsIndexRoute
  '/patients/$patientId/lab-trends': typeof PatientsPatientIdLabTrendsRoute
  '/patients/$patientId/upload': typeof PatientsPatientIdUploadRoute
  '/patients/$patientId/wearables': typeof PatientsPatientIdWearablesRoute
  '/patients/$patientId/': typeof PatientsPatientIdIndexRoute
  '/patients/$patientId/domains/$domainKey': typeof PatientsPatientIdDomainsDomainKeyRoute
  '/patients/$patientId/reports/$sessionId': typeof PatientsPatientIdReportsSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/patients': typeof PatientsIndexRoute
  '/patients/$patientId/lab-trends': typeof PatientsPatientIdLabTrendsRoute
  '/patients/$patientId/upload': typeof PatientsPatientIdUploadRoute
  '/patients/$patientId/wearables': typeof PatientsPatientIdWearablesRoute
  '/patients/$patientId': typeof PatientsPatientIdIndexRoute
  '/patients/$patientId/domains/$domainKey': typeof PatientsPatientIdDomainsDomainKeyRoute
  '/patients/$patientId/reports/$sessionId': typeof PatientsPatientIdReportsSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/patients/$patientId': typeof PatientsPatientIdRouteRouteWithChildren
  '/patients/': typeof PatientsIndexRoute
  '/patients/$patientId/lab-trends': typeof PatientsPatientIdLabTrendsRoute
  '/patients/$patientId/upload': typeof PatientsPatientIdUploadRoute
  '/patients/$patientId/wearables': typeof PatientsPatientIdWearablesRoute
  '/patients/$patientId/': typeof PatientsPatientIdIndexRoute
  '/patients/$patientId/domains/$domainKey': typeof PatientsPatientIdDomainsDomainKeyRoute
  '/patients/$patientId/reports/$sessionId': typeof PatientsPatientIdReportsSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/patients/$patientId'
    | '/patients/'
    | '/patients/$patientId/lab-trends'
    | '/patients/$patientId/upload'
    | '/patients/$patientId/wearables'
    | '/patients/$patientId/'
    | '/patients/$patientId/domains/$domainKey'
    | '/patients/$patientId/reports/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/patients'
    | '/patients/$patientId/lab-trends'
    | '/patients/$patientId/upload'
    | '/patients/$patientId/wearables'
    | '/patients/$patientId'
    | '/patients/$patientId/domains/$domainKey'
    | '/patients/$patientId/reports/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/patients/$patientId'
    | '/patients/'
    | '/patients/$patientId/lab-trends'
    | '/patients/$patientId/upload'
    | '/patients/$patientId/wearables'
    | '/patients/$patientId/'
    | '/patients/$patientId/domains/$domainKey'
    | '/patients/$patientId/reports/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PatientsPatientIdRouteRoute: typeof PatientsPatientIdRouteRouteWithChildren
  PatientsIndexRoute: typeof PatientsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/': {
      id: '/patients/'
      path: '/patients'
      fullPath: '/patients/'
      preLoaderRoute: typeof PatientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/$patientId': {
      id: '/patients/$patientId'
      path: '/patients/$patientId'
      fullPath: '/patients/$patientId'
      preLoaderRoute: typeof PatientsPatientIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/$patientId/': {
      id: '/patients/$patientId/'
      path: '/'
      fullPath: '/patients/$patientId/'
      preLoaderRoute: typeof PatientsPatientIdIndexRouteImport
      parentRoute: typeof PatientsPatientIdRouteRoute
    }
    '/patients/$patientId/lab-trends': {
      id: '/patients/$patientId/lab-trends'
      path: '/lab-trends'
      fullPath: '/patients/$patientId/lab-trends'
      preLoaderRoute: typeof PatientsPatientIdLabTrendsRouteImport
      parentRoute: typeof PatientsPatientIdRouteRoute
    }
    '/patients/$patientId/upload': {
      id: '/patients/$patientId/upload'
      path: '/upload'
      fullPath: '/patients/$patientId/upload'
      preLoaderRoute: typeof PatientsPatientIdUploadRouteImport
      parentRoute: typeof PatientsPatientIdRouteRoute
    }
    '/patients/$patientId/wearables': {
      id: '/patients/$patientId/wearables'
      path: '/wearables'
      fullPath: '/patients/$patientId/wearables'
      preLoaderRoute: typeof PatientsPatientIdWearablesRouteImport
      parentRoute: typeof PatientsPatientIdRouteRoute
    }
    '/patients/$patientId/domains/$domainKey': {
      id: '/patients/$patientId/domains/$domainKey'
      path: '/domains/$domainKey'
      fullPath: '/patients/$patientId/domains/$domainKey'
      preLoaderRoute: typeof PatientsPatientIdDomainsDomainKeyRouteImport
      parentRoute: typeof PatientsPatientIdRouteRoute
    }
    '/patients/$patientId/reports/$sessionId': {
      id: '/patients/$patientId/reports/$sessionId'
      path: '/reports/$sessionId'
      fullPath: '/patients/$patientId/reports/$sessionId'
      preLoaderRoute: typeof PatientsPatientIdReportsSessionIdRouteImport
      parentRoute: typeof PatientsPatientIdRouteRoute
    }
  }
}

interface PatientsPatientIdRouteRouteChildren {
  PatientsPatientIdLabTrendsRoute: typeof PatientsPatientIdLabTrendsRoute
  PatientsPatientIdUploadRoute: typeof PatientsPatientIdUploadRoute
  PatientsPatientIdWearablesRoute: typeof PatientsPatientIdWearablesRoute
  PatientsPatientIdIndexRoute: typeof PatientsPatientIdIndexRoute
  PatientsPatientIdDomainsDomainKeyRoute: typeof PatientsPatientIdDomainsDomainKeyRoute
  PatientsPatientIdReportsSessionIdRoute: typeof PatientsPatientIdReportsSessionIdRoute
}

const PatientsPatientIdRouteRouteChildren: PatientsPatientIdRouteRouteChildren =
  {
    PatientsPatientIdLabTrendsRoute: PatientsPatientIdLabTrendsRoute,
    PatientsPatientIdUploadRoute: PatientsPatientIdUploadRoute,
    PatientsPatientIdWearablesRoute: PatientsPatientIdWearablesRoute,
    PatientsPatientIdIndexRoute: PatientsPatientIdIndexRoute,
    PatientsPatientIdDomainsDomainKeyRoute:
      PatientsPatientIdDomainsDomainKeyRoute,
    PatientsPatientIdReportsSessionIdRoute:
      PatientsPatientIdReportsSessionIdRoute,
  }

const PatientsPatientIdRouteRouteWithChildren =
  PatientsPatientIdRouteRoute._addFileChildren(
    PatientsPatientIdRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PatientsPatientIdRouteRoute: PatientsPatientIdRouteRouteWithChildren,
  PatientsIndexRoute: PatientsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
